name             'dotfiles'
maintainer       'miku'
maintainer_email 'miku@miku.io'
license          'All rights reserved'
description      'Installs/Configures dotfiles'
long_description 'Installs/Configures dotfiles'
version          '0.1.0'

depends 'git'
depends 'homebrewalt'
